sudo: required
services: 
  - docker

before_install: 
    - docker build -t volodymyrholoida/react-client-test -f ./client/Dockerfile.dev .

script: 
  - docker run -e CI=true volodymyrholoida/react-client-test -f ./client/Dockerfile.dev npm run test

after_success: 
  - docker build -t volodymyrholoida/multi-client ./client
  - docker build -t volodymyrholoida/multi-server ./server
  - docker build -t volodymyrholoida/multi-worker ./worker
  - docker build -t volodymyrholoida/multi-nginx ./nginx

# deploy:
#   provider: elasticbeanstalk
#   region: "eu-north-1"
#   app: "frontend"
#   env: "Frontend-env"
#   bucket_name: "elasticbeanstalk-eu-north-1-376750145167"
#   bucket-path: "docker"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: "$AWS_SECRET_KEY"