sudo: required
services: 
  - docker

before_install: 
    - docker build -t vowkaz16072004/react-client-test -f ./client/Dockerfile.dev .

script: 
  - docker run -e CI=true vowkaz16072004/react-client-test -f ./client/Dockerfile.dev npm run test

after_success: 
  - docker build -t vowkaz16072004/multi-client ./client
  - docker build -t vowkaz16072004/multi-server ./server
  - docker build -t vowkaz16072004/multi-worker ./worker
  - docker build -t vowkaz16072004/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vowkaz16072004/multi-client
  - docker push vowkaz16072004/multi-server
  - docker push vowkaz16072004/multi-worker
  - docker push vowkaz16072004/multi-nginx